### ISSUE TITLE
Add wildcard filter, please :3

### ISSUE THREAD

**Issue by StarveTheEgo** [erichard/elasticsearch-query-builder#1]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

This one! :-) Not that much to code

So i will not have to some custom local extend of this project

**Comment by erichard** [comment]
Don't hesitate to submit a PR if you need this quickly

**Comment by StarveTheEgo** [comment]
Pull request: #2

My first PR ever, don`t mind :)

**Comment by StarveTheEgo** [comment]
Thanks!
