### ISSUE TITLE
v3 current status

### ISSUE THREAD

**Issue by igoooor** [erichard/elasticsearch-query-builder#16]
Sorry for that silly question but I am a bit confused.
What we see in the README.md on `main` branch is not implemented fully yet right?
For example I don't find that method yet:
```
$query->addFilter($boolFilter);
```
I'm just asking to be sure I get it correctly. I don't intend to put pressure or anything 🙌

**Comment by erichard** [comment]
The v3 is there but it is beta for the moment. You can get it with 

    composer require erichard/elasticsearch-query-builder "^3.0@beta"

**Comment by erichard** [comment]
My mistake, in fact you have right. The README was not up to date. I fixed it.

**Comment by igoooor** [comment]
thank you 🙏🏻
